
import { Service, TranslationSet } from './types';

export const GOOGLE_APP_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbxNIDoX3P7dXhpHriuNZ2L8RVY5QfTzsgvP_L0u8SQMVJU-UvmC7_1Ilbk5cW-_qttb8Q/exec';
export const STUDIO_WHATSAPP_NUMBER = '6581566068';

export const services: Service[] = [
    {
        id: 'collagen',
        isPromo: true,
        image: 'https://www.wearebodybeautiful.com/wp-content/uploads/2020/02/Ultrasound-phonophoresis-facials-101.jpg',
        titleKey: 'service1Title',
        descriptionKey: 'service1Desc',
        priceKey: 'service1PriceNew',
        oldPriceKey: 'service1PriceOld',
    },
    {
        id: 'purifying',
        image: 'https://www.glam.com/img/gallery/are-extractions-a-must-for-healthy-skin-heres-what-we-know/intro-1678298204.jpg',
        titleKey: 'service2Title',
        descriptionKey: 'service2Desc',
        priceKey: 'service2Price',
    },
    {
        id: 'hydrating',
        image: 'https://i.postimg.cc/HnNJgvG9/513abf82-5406-40dd-aa9c-9f19ee313d18.jpg',
        titleKey: 'service3Title',
        descriptionKey: 'service3Desc',
        priceKey: 'service3Price',
    },
    {
        id: 'whitening',
        image: 'https://skintrends.ph/cdn/shop/products/WhiteningFacial.jpg?v=1621581601',
        titleKey: 'service4Title',
        descriptionKey: 'service4Desc',
        priceKey: 'service4Price',
    },
    {
        id: 'acne',
        image: 'https://i.postimg.cc/SxcxbyhT/531ba73c-92fc-45aa-a1fb-9c085dce310b.jpg',
        titleKey: 'service5Title',
        descriptionKey: 'service5Desc',
        priceKey: 'service5Price',
    },
    {
        id: 'rf',
        image: 'https://pica.zhimg.com/v2-d02188510f60bce633ee4da8f7c834b8_1440w.jpg',
        titleKey: 'service6Title',
        descriptionKey: 'service6Desc',
        priceKey: 'service6Price',
    },
     {
        id: 'detox',
        image: 'https://nasiedu.com/wp-content/uploads/2018/05/service_antiage-750x500-1.jpeg',
        titleKey: 'service7Title',
        descriptionKey: 'service7Desc',
        priceKey: 'service7Price',
        colSpan: 'md:col-span-2 lg:col-span-3',
    },
];

export const aboutCarouselImages = [
    'https://i.postimg.cc/3NVkV67g/Whats-App-Image-2025-05-12-at-10-35-29-PM-2.jpg',
    'https://i.postimg.cc/brsG68Xy/Whats-App-Image-2025-05-12-at-10-35-29-PM.jpg',
    'https://i.postimg.cc/NFMXWmXw/Whats-App-Image-2025-05-12-at-10-35-28-PM.jpg',
    'https://i.postimg.cc/tTJNWKgb/Whats-App-Image-2025-05-12-at-10-06-55-PM.jpg',
    'https://i.postimg.cc/FRPdgzBC/Whats-App-Image-2025-05-12-at-10-35-29-PM-1.jpg',
];

export const translations: TranslationSet = {
    en: {
        navHome: "Home",
        navServices: "Services",
        navAbout: "About",
        navReviews: "Reviews",
        navContact: "Contact",
        navBookNow: "Book Now",
        navStudioName: "Beauty Studio", 
        heroTitle: "Your Sanctuary for Beauty",
        heroSubtitle: "Discover bespoke treatments at JW Beauty Studio, where luxury meets comfort in a private home setting.",
        promoBannerTitle: "First Time Here? Enjoy a Special Welcome Offer!",
        promoBannerDesc: "Try our signature <strong>Collagen Plus Treatment</strong> for just <span class=\"text-2xl font-bold text-[#E29578]\">$68</span> (U.P. $88).",
        promoBannerButton: "Claim Your Welcome Offer",
        servicesTitle: "Our Signature Treatments",
        service1Title: "New Customer Special: Collagen Plus Treatment",
        service1Desc: "Revitalize your skin with our special introductory offer for a luxurious collagen-boosting facial, utilizing two advanced machines. Enhance elasticity and achieve a youthful glow.",
        service1PriceOld: "$88",
        service1PriceNew: "$68",
        promoBadge: "Promo",
        service2Title: "Deep Pore Purifying Treatment",
        service2Desc: "Experience a deep cleanse that purifies your skin from the inside out. This essential treatment focuses on congested pores, drawing out impurities and blackheads to reveal a noticeably clearer and smoother complexion. Includes a scrubber and crystal ball application.",
        service2Price: "Price: $58",
        service3Title: "Hydrating Facial Trial",
        service3Desc: "Experience intense hydration with our trial facial. This treatment deeply replenishes moisture, leaving your skin supple, dewy, and radiantly refreshed. Ideal for all skin types.",
        service3Price: "Price: $68",
        service4Title: "Whitening Treatment",
        service4Desc: "Achieve a brighter, more even skin tone. Our specialized whitening treatment targets pigmentation and dullness, revealing a luminous, clear complexion.",
        service4Price: "Price: $108",
        service5Title: "Acne Treatment",
        service5Desc: "Combat breakouts and soothe irritated skin. Our targeted acne treatment helps to reduce inflammation, clear pores, and promote healing for a healthier appearance.",
        service5Price: "Price: $108",
        service6Title: "RF Treatment Anti-Aging",
        service6Desc: "Turn back the clock with advanced Radio Frequency technology. This non-invasive treatment effectively tightens skin, reduces the appearance of wrinkles, and stimulates natural collagen production.",
        service6Price: "Price: $88",
        service7Title: "Deep Detox Trio", 
        service7Desc: "A comprehensive treatment to deeply detoxify, rejuvenate, and refresh your skin. Combines multiple techniques for maximum revitalizing results, leaving you utterly renewed.",
        service7Price: "Price: $128",
        aboutTitle: "Discover JW Beauty Studio",
        aboutP1: "Welcome to JW Beauty Studio, your personal oasis for beauty and relaxation, nestled in the comfort and privacy of a home environment. Founded by Reina in 2025, our mission is to provide high-quality, personalized beauty services that make you feel confident, cherished, and rejuvenated.",
        aboutP2: "As a certified beauty therapist with 13 years of experience, I am deeply passionate about the art of beauty and helping clients achieve their aesthetic goals. At JW Beauty Studio, only professional-grade products are used, and the highest standards of hygiene and care are meticulously maintained. I believe beauty treatments should be a tranquil, enjoyable, and uplifting experience.",
        aboutP3: "Come and experience the difference of a dedicated, one-on-one service, thoughtfully tailored just for you.",
        reviewsTitle: "What Our Clients Say",
        contactTitle: "Get In Touch",
        contactStudioName: "JW Beauty Studio",
        contactAddress: "450C Bukit Batok West Ave #03-623, Singapore 653450",
        contactWhatsappLabel: "WhatsApp for Bookings:",
        contactHoursNote: "We are open everyday from 9 AM to 10 PM. We look forward to welcoming you!",
        bookingTitle: "Request Your Appointment",
        formName: "Full Name",
        formNamePlaceholder: "e.g., Jane Doe",
        formPhone: "Phone Number",
        formPhonePlaceholder: "e.g., 81234567",
        formService: "Select Service",
        formServiceOptionDefault: "-- Choose a Service --",
        formServiceOption1: "New Customer Special: Collagen Plus Treatment",
        formServiceOption2: "Deep Pore Purifying Treatment",
        formServiceOption3: "Hydrating Facial Trial",
        formServiceOption4: "Whitening Treatment",
        formServiceOption5: "Acne Treatment",
        formServiceOption6: "RF Treatment Anti-Aging",
        formServiceOption7: "Deep Detox Trio", 
        formServiceOptionNotSure: "I'm not sure / Need consultation",
        formServiceOptionOther: "Other",
        formDate: "Preferred Date",
        formTime: "Preferred Time Slot",
        formTimeOptionDefault: "-- Select Time --",
        formTimeOptionMorning: "Morning (9AM - 12PM)",
        formTimeOptionAfternoon: "Afternoon (1PM - 5PM)",
        formTimeOptionEvening: "Evening (6PM - 10PM)",
        formTimeMorning: "Morning",
        formTimeAfternoon: "Afternoon",
        formTimeEvening: "Evening",
        formSubmitButton: "Request on WhatsApp",
        footerRights: `© ${new Date().getFullYear()} JW Beauty Studio. All Rights Reserved.`,
        footerAddress: "450C Bukit Batok West Ave #03-623, Singapore 653450",
        footerTagline: "Crafted with <span class=\"text-[#E29578]\">&hearts;</span> for your beauty journey.",
        modalOkButton: "OK",
        alertSpreadsheetError: "Booking system (Spreadsheet) is not configured by the site owner. Please contact the studio.",
        alertWhatsAppError: "Booking system (WhatsApp) is not configured by the site owner. Please contact the studio.",
        alertFormError: "A critical form error occurred on the page. Please refresh and try again. If the issue persists, contact the studio.",
        alertNetworkErrorSpreadsheet: "A network error occurred sending to our booking system. Proceeding with WhatsApp.",
        alertRequestSent: "Your request is ready! Please tap 'Send' in WhatsApp to confirm. We will reply to you shortly.",
        feedbackProcessing: "Processing your request...",
        feedbackSpreadsheetSent: "Request sent to booking system. Preparing WhatsApp message...",
        feedbackSpreadsheetError: "Network error sending to booking system. Preparing WhatsApp message...",
        feedbackWhatsAppReady: "Your booking request is prepared! Please tap 'Send' in WhatsApp. We will reply to you shortly.",
        whatsappChat: "Chat with us",
        aiAdvisorTitle: "AI Skincare Advisor",
        aiAdvisorSubtitle: "Have questions about your skin? Get instant advice from our AI-powered assistant. Ask about skin types, concerns, or treatment options.",
        aiWelcomeMessage: "How can I help your skin today?",
        aiWelcomeExample: `e.g., "I have dry, flaky skin."`,
        aiInputPlaceholder: "Ask a skincare question...",
        aiError: "I'm sorry, I'm having trouble connecting right now. Please try again later.",
    },
    zh: {
        navHome: "首页",
        navServices: "服务项目",
        navAbout: "关于我们",
        navReviews: "客户评价",
        navContact: "联系方式",
        navBookNow: "立即预约",
        navStudioName: "美容工作室", 
        heroTitle: "您的专属美丽殿堂",
        heroSubtitle: "在JW美容工作室，体验顶级美容护理，享受家一般的舒适、私密与奢华。",
        promoBannerTitle: "首次光临？享受特别欢迎优惠！",
        promoBannerDesc: "体验我们的招牌 <strong class=\"font-semibold\">胶原蛋白增值护理</strong>，仅需 <span class=\"text-2xl font-bold text-[#E29578]\">$68</span> (原价 $88)。",
        promoBannerButton: "领取欢迎优惠",
        servicesTitle: "我们的特色护理",
        service1Title: "新客户优惠：胶原蛋白护理",
        service1Desc: "体验我们特别推出的豪华胶原蛋白增效面部护理，采用两台先进仪器。焕活您的肌肤，增强弹性，重焕年轻光彩。",
        service1PriceOld: "$88",
        service1PriceNew: "$68",
        promoBadge: "促销",
        service2Title: "深层毛孔净化护理",
        service2Desc: "体验深层清洁，由内而外净化您的肌肤。此基础护理专注于疏通堵塞毛孔，清除杂质和黑头，令肌肤明显更清透、更光滑。包含磨砂和水晶球护理。",
        service2Price: "价格：$58",
        service3Title: "补水面部护理体验",
        service3Desc: "体验强效补水。此体验面部护理深层补充水分，令肌肤水嫩、莹润、焕发光彩。适合所有肤质。",
        service3Price: "价格：$68",
        service4Title: "美白护理",
        service4Desc: "实现更明亮、更均匀的肤色。我们专业的美白护理针对色素沉着和暗沉，打造透亮无瑕的肌肤。",
        service4Price: "价格：$108",
        service5Title: "祛痘护理",
        service5Desc: "对抗痘痘爆发，舒缓受刺激的肌肤。我们针对性的祛痘护理有助于减少炎症、清洁毛孔、促进愈合，重现健康肌肤。",
        service5Price: "价格：$108",
        service6Title: "RF射频抗衰老护理",
        service6Desc: "借助先进的射频技术逆转时光。这种非侵入性治疗可有效紧致肌肤、减少皱纹并刺激胶原蛋白自然生成。",
        service6Price: "价格：$88",
        service7Title: "深层排毒三重奏", 
        service7Desc: "全面护理，深层排毒、焕活并清爽您的肌肤。结合多种技术，实现最佳焕活效果，令您焕然一新。",
        service7Price: "价格：$128",
        aboutTitle: "了解JW美容工作室",
        aboutP1: "欢迎来到JW美容工作室——您专属的美丽与放松绿洲，坐落于舒适私密的家庭环境中。由 Reina 于2025年创立，我们的使命是提供高品质、个性化的美容服务，让您倍感自信、珍爱与焕发活力。",
        aboutP2: "作为一名拥有13年经验的认证美容治疗师，我對美容艺术充满热情，并致力于帮助客户实现其审美目标。在JW美容工作室，我们仅使用专业级产品，并严格遵守最高的卫生和护理标准。我相信美容治疗应该是一种宁静、愉悦和令人振奋的体验。",
        aboutP3: "来体验专为您精心打造的一对一专属服务，感受与众不同。",
        reviewsTitle: "客户怎么说",
        contactTitle: "联系我们",
        contactStudioName: "JW美容工作室",
        contactAddress: "450C Bukit Batok West Ave #03-623, Singapore 653450",
        contactWhatsappLabel: "WhatsApp预约：",
        contactHoursNote: "我们每天上午9点至晚上10点营业。期待您的光临！",
        bookingTitle: "预约您的护理时间",
        formName: "全名",
        formNamePlaceholder: "例如：陈芳",
        formPhone: "电话号码",
        formPhonePlaceholder: "例如：81234567",
        formService: "选择服务项目",
        formServiceOptionDefault: "-- 请选择服务 --",
        formServiceOption1: "新客户优惠：胶原蛋白护理",
        formServiceOption2: "深层毛孔净化护理",
        formServiceOption3: "补水面部护理体验",
        formServiceOption4: "美白护理",
        formServiceOption5: "祛痘护理",
        formServiceOption6: "RF射频抗衰老护理",
        formServiceOption7: "深层排毒三重奏", 
        formServiceOptionNotSure: "不确定/需要咨询",
        formServiceOptionOther: "其他",
        formDate: "首选日期",
        formTime: "首选时间段",
        formTimeOptionDefault: "-- 请选择时间 --",
        formTimeOptionMorning: "上午 (9点 - 12点)",
        formTimeOptionAfternoon: "下午 (1点 - 5点)",
        formTimeOptionEvening: "傍晚 (6点 - 10点)",
        formTimeMorning: "上午",
        formTimeAfternoon: "下午",
        formTimeEvening: "傍晚",
        formSubmitButton: "通过WhatsApp预约",
        footerRights: `© ${new Date().getFullYear()} JW美容工作室. 版权所有.`, 
        footerAddress: "450C Bukit Batok West Ave #03-623, Singapore 653450",
        footerTagline: "用心呵护您的美丽旅程 <span class=\"text-[#E29578]\">&hearts;</span>",
        modalOkButton: "好的",
        alertSpreadsheetError: "预约系统（表格）未正确配置。请联系工作室。",
        alertWhatsAppError: "预约系统（WhatsApp）未正确配置。请联系工作室。",
        alertFormError: "表格出现严重错误。请刷新页面后重试。如果问题仍然存在，请联系工作室。",
        alertNetworkErrorSpreadsheet: "发送至我们预约系统时发生网络错误。将继续尝试通过WhatsApp发送您的请求。",
        alertRequestSent: "您的请求已准备好！请在WhatsApp中点击“发送”进行确认。我们会尽快回复您。",
        feedbackProcessing: "正在处理您的请求...",
        feedbackSpreadsheetSent: "请求已发送至预约系统。正在准备WhatsApp消息...",
        feedbackSpreadsheetError: "发送至预约系统时发生网络错误。正在准备WhatsApp消息...",
        feedbackWhatsAppReady: "您的预约请求已准备好！请在WhatsApp中点击“发送”。我们会尽快回复您。",
        whatsappChat: "与我们聊天",
        aiAdvisorTitle: "AI 护肤顾问",
        aiAdvisorSubtitle: "对您的皮肤有疑问吗？从我们的AI助手那里获得即时建议。可以询问关于皮肤类型、问题或护理方案。",
        aiWelcomeMessage: "今天我能为您的皮肤做些什么？",
        aiWelcomeExample: "例如：“我的皮肤很干，还脱皮。”",
        aiInputPlaceholder: "请输入您的护肤问题...",
        aiError: "抱歉，我现在无法连接。请稍后再试。",
    }
};